#一个mod,一个server端+hl2dm
name: my_build_win32--2023

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build-srceng-server-win-32-hl2dm:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build-sv
      run: |
        
        git submodule init;git submodule update
        #sudo apt update;sudo apt upgrade;sudo apt-get install -f -y gdb libopenal-dev g++-multilib gcc-multilib libpng-dev libjpeg-dev libfreetype6-dev libfontconfig1-dev libcurl4-gnutls-dev libsdl2-dev zlib1g-dev libbz2-dev libedit-dev
        ./waf.bat configure -T debug --prefix=./win --disable-warns -d
        ./waf.bat install -j4
        
        cat build/config.log >./win/info.txt
        
    - uses: actions/upload-artifact@v3
      with:
        name: win32-hl2dm-server
        path: ./win
        if-no-files-found: error


  build-srceng-win-hl2dm:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        #
        git submodule init;git submodule update
        ./waf.bat configure -T debug -8 --prefix=./win --disable-warns --build-game=hl2mp 
        
        ./waf.bat install -j4
        cat build/config.log > ./win/info.txt
    - uses: actions/upload-artifact@v3
      with:
        name: hl2dm-win32
        path: ./win
        if-no-files-found: error
